name: metastatic-haskell-parser
version: 0.1.0.0
synopsis: Haskell parser for Metastatic

dependencies:
- base >= 4.7 && < 5
- haskell-src-exts >= 1.23
- aeson >= 2.0
- text >= 1.2
- bytestring >= 0.10

executables:
  parser:
    main: Parser.hs
    source-dirs: .
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
